version: '3.3'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: badminton
      MYSQL_USER: user
      MYSQL_PASSWORD: rootpassword
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service
    environment:
      DB_HOST: db
      DB_PORT: 3308
      DB_USER: root
      DB_PASSWORD: 123456
      DB_NAME: badminton
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data: